
#ifndef IOCTL_CONTROLCODES_H
#define IOCTL_CONTROLCODES_H

#define IO_SET_PID CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SET_ACCESSMASK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#endif